name = "hack-nf-mono"
version = "3.4.0"
description = "Nerd Fonts patched 'Hack' Font family. (Monospace version, Nerd Fonts Symbol/Icon will be always 1 cell wide)"
homepage = "https://github.com/ryanoasis/nerd-fonts"
license = "MIT"
type = "archive"
bin = ["hack-nf-mono.exe"]

[architecture.x64]
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip"
hash = "sha256:8ca33a60c791392d872b80d26c42f2bfa914a480f9eb2d7516d9f84373c36897"
