name = "bun"
version = "1.4.0"
description = "Incredibly fast JavaScript runtime, bundler, transpiler and package manager - all in one."
homepage = "https://bun.sh/"
license = "MIT"
type = "archive"
bin = ["bun.exe", "bun.exe"]

[architecture.x64]
url = "https://github.com/oven-sh/bun/releases/download/bun-v1.4.0/bun-windows-x64.zip"
hash = "sha256:e6f093d39da486b20262ca8cdd5ed6a9e8bc9c2f275b78e6d3a0c5b28cc95901"
