name = "bun"
version = "1.4.1"
description = "Incredibly fast JavaScript runtime, bundler, transpiler and package manager - all in one."
homepage = "https://bun.sh/"
license = "MIT"
type = "archive"
bin = ["bun.exe", "bun.exe"]

[architecture.x64]
url = "https://github.com/oven-sh/bun/releases/download/bun-v1.4.1/bun-windows-x64.zip"
hash = "sha256:52b1f3028b01f43d37fefdf669d034a1ee2e0d96c56bb13c393bdaf169b1af84"
