name = "pandoc"
version = "3.10"
description = "Universal markup converter"
homepage = "https://pandoc.org"
license = "GPL-2.0-or-later"
type = "archive"
bin = ["pandoc.exe"]

[architecture.x64]
url = "https://github.com/jgm/pandoc/releases/download/3.10/pandoc-3.10-windows-x86_64.zip"
hash = "sha256:bb808d00fd58762299d64582a9b4c3e4b106cd929e62c5f19bcdcb496f1e54ae"
