name = "pandoc"
version = "3.11"
description = "Universal markup converter"
homepage = "https://pandoc.org"
license = "GPL-2.0-or-later"
type = "archive"
bin = ["pandoc.exe"]

[architecture.x64]
url = "https://github.com/jgm/pandoc/releases/download/3.11/pandoc-3.11-windows-x86_64.zip"
hash = "sha256:2ab72baf2399450e148ddf7a2a8689806c42e1bba71862b57e220fd9b8456d3d"
