name = "frpc-desktop"
version = "1.2.7"
description = "frp跨平台桌面客户端，可视化配置，轻松实现内网穿透！ 支持所有frp版本"
homepage = "https://jwinks.com/p/frp/"
license = "MIT"
type = "archive"
bin = ["Frpc-Desktop.exe"]

[architecture.x64]
url = "https://github.com/luckjiawei/frpc-desktop/releases/download/v1.2.7/Frpc-Desktop-1.2.7.exe#/dl.7z"
hash = "sha256:aa2b70db59265ec3bb2d1961b520e0beca8156bd08971a81885b8d965bf19400"
