name = "codex"
version = "0.150.1"
description = "OpenAI's Codex AI coding assistant"
homepage = "https://github.com/openai/codex"
license = "Apache-2.0"
type = "archive"
bin = ["codex.exe"]

[architecture.x64]
url = "https://github.com/openai/codex/releases/download/rust-v0.150.1/codex-x86_64-pc-windows-msvc.exe#/codex.exe"
hash = "sha256:cbd657ddfe151d1a6ebad660beffdbd3265dc5aff4b3a6095124d3e2f0156f2f"
