name = "gh"
version = "2.97.0"
description = "Official GitHub CLI"
homepage = "https://cli.github.com"
license = "MIT"
type = "archive"
bin = ["bin\\gh.exe"]

[architecture.x64]
url = "https://github.com/cli/cli/releases/download/v2.97.0/gh_2.97.0_windows_amd64.zip"
hash = "sha256:35d7fe05c4dd1411ffda1e73dfc7c6f44b75c936ca51fa6595c657fdc0350cec"
