name = "gh"
version = "2.98.0"
description = "Official GitHub CLI"
homepage = "https://cli.github.com"
license = "MIT"
type = "archive"
bin = ["bin\\gh.exe"]

[architecture.x64]
url = "https://github.com/cli/cli/releases/download/v2.98.0/gh_2.98.0_windows_amd64.zip"
hash = "sha256:c28c7b3b584967a05b74d9eaf7481bff24ddc34930bf2d6e442c148236561eb1"
