name = "mise"
version = "2026.6.10"
description = "Polyglot tool version manager and task runner"
homepage = "https://mise.jdx.dev/"
license = "MIT"
type = "archive"
bin = ["bin/mise.exe"]

[architecture.x64]
url = "https://github.com/jdx/mise/releases/download/v2026.6.10/mise-v2026.6.10-windows-x64.zip"
hash = "sha256:cfdc9d11ceae211220bf68514c1d7fc67374a26cfbfb62ffeed10922cc1f6ec7"
extract_dir = "mise"
