name = "mise"
version = "2026.10.3"
description = "Polyglot tool version manager and task runner"
homepage = "https://mise.jdx.dev/"
license = "MIT"
type = "archive"
bin = ["bin/mise.exe"]

[architecture.x64]
url = "https://github.com/jdx/mise/releases/download/v2026.10.3/mise-v2026.10.3-windows-x64.zip"
hash = "sha256:af5cad4d381c4e06e9c488af86ad3d3159474ffa7a18e061436a408f7262f23a"
extract_dir = "mise"
