name = "neovim"
version = "0.12.2"
description = "Vim-fork focused on extensibility and usability"
homepage = "https://neovim.io/"
license = "Apache-2.0,Vim"
type = "archive"
bin = ["bin\\nvim.exe", "bin\\xxd.exe"]

[architecture.x64]
url = "https://github.com/neovim/neovim/releases/download/v0.12.2/nvim-win64.zip"
hash = "sha256:23fe150edbcc976eabe55092e1e9d2e5e237afde69553d170e936f776b405d53"
extract_dir = "nvim-win64"
