name = "psmux"
version = "3.3.6"
description = "Terminal multiplexer for Windows - tmux alternative for PowerShell and Windows Terminal"
homepage = "https://psmux.pages.dev"
license = "MIT"
type = "archive"
bin = ["psmux.exe", "pmux.exe", "tmux.exe"]

[architecture.x64]
url = "https://github.com/psmux/psmux/releases/download/v3.3.6/psmux-v3.3.6-windows-x64.zip"
hash = "sha256:a56a890ea0829567818b9a368f16dcbd39c087f27328573df17c10dd39618947"
