name = "cherry-studio"
version = "1.9.11"
description = "A desktop client that supports for multiple LLM providers."
homepage = "https://cherry-ai.com"
license = "Apache-2.0"
type = "archive"
bin = ["cherry-studio.exe"]

[architecture.x64]
url = "https://github.com/CherryHQ/cherry-studio/releases/download/v1.9.11/Cherry-Studio-1.9.11-x64-portable.exe#/cherry-studio.exe"
hash = "sha256:114c4f6ffde670eb4793976643d7039aec6e13755fc009df61b535b2b90ed348"
