name = "cherry-studio"
version = "2.0.0"
description = "A desktop client that supports for multiple LLM providers."
homepage = "https://cherry-ai.com"
license = "Apache-2.0"
type = "archive"
bin = ["cherry-studio.exe"]

[architecture.x64]
url = "https://github.com/CherryHQ/cherry-studio/releases/download/v2.0.0/Cherry-Studio-2.0.0-x64-portable.exe#/cherry-studio.exe"
hash = "sha256:eb1806cc41ec44f7399099914f4f2d4c743d894292246e69c73f82e52f12f7cf"
