name = "cherry-studio"
version = "1.9.9"
description = "A desktop client that supports for multiple LLM providers."
homepage = "https://cherry-ai.com"
license = "Apache-2.0"
type = "archive"
bin = ["cherry-studio.exe"]

[architecture.x64]
url = "https://github.com/CherryHQ/cherry-studio/releases/download/v1.9.9/Cherry-Studio-1.9.9-x64-portable.exe#/cherry-studio.exe"
hash = "sha256:f3e8a0a392ffd4b20d2b989e379f96f236fd4a1e6d0e684986d58fdd0e42810a"
