name = "gemini-cli"
version = "0.45.2"
description = "Brings the power of Gemini directly into your terminal"
homepage = "https://geminicli.com"
license = "Apache-2.0"
type = "installer"
installer = "npm"
bin = ["gemini"]

[architecture.x64]
url = "npm:@google/gemini-cli"
hash = "sha256:"
