name = "oh-my-pi"
version = "18.0.3"
description = "AI Coding agent for the terminal — hash-anchored edits, optimized tool harness, LSP, Python, browser, subagents, and more (fork of pi)."
homepage = "https://github.com/can1357/oh-my-pi"
license = "MIT"
type = "archive"
bin = ["omp.exe"]

[architecture.x64]
url = "https://github.com/can1357/oh-my-pi/releases/download/v18.0.3/omp-windows-x64.exe#/omp.exe"
hash = "sha256:63c5bb8c517c83c838a6283e36a56faa3c1071e3a5eba145266fc723838c57b5"
