name = "oh-my-pi"
version = "17.0.6"
description = "AI Coding agent for the terminal — hash-anchored edits, optimized tool harness, LSP, Python, browser, subagents, and more (fork of pi)."
homepage = "https://github.com/can1357/oh-my-pi"
license = "MIT"
type = "archive"
bin = ["omp.exe"]

[architecture.x64]
url = "https://github.com/can1357/oh-my-pi/releases/download/v17.0.6/omp-windows-x64.exe#/omp.exe"
hash = "sha256:b5c7a5b008ae2342664161ed5615337501ae833a7ce825dbbf0918281dafb2d6"
