name = "pixi"
version = "0.71.1"
description = "Package management made easy"
homepage = "https://pixi.sh"
license = "BSD-3-Clause"
type = "archive"
bin = ["pixi.exe"]

[architecture.x64]
url = "https://github.com/prefix-dev/pixi/releases/download/v0.71.1/pixi-x86_64-pc-windows-msvc.zip"
hash = "sha256:6b6692588ac67a38ac4804ad1e7e41f838cce9cbe61686649576f0ee307968bc"
