name = "pixi"
version = "0.73.0"
description = "Package management made easy"
homepage = "https://pixi.sh"
license = "BSD-3-Clause"
type = "archive"
bin = ["pixi.exe"]

[architecture.x64]
url = "https://github.com/prefix-dev/pixi/releases/download/v0.73.0/pixi-x86_64-pc-windows-msvc.zip"
hash = "sha256:d9044186bfea9771b8e35b0ed032352b557a82528cd5165db6b8ad137c7a873c"
