name = "uv"
version = "0.12.21"
description = "An extremely fast Python package installer and resolver, written in Rust."
homepage = "https://docs.astral.sh/uv/"
license = "Apache-2.0|MIT"
type = "archive"
bin = ["uv.exe", "uvx.exe", "uvw.exe"]

[architecture.x64]
url = "https://github.com/astral-sh/uv/releases/download/0.12.21/uv-x86_64-pc-windows-msvc.zip"
hash = "sha256:5d223efa0bf00208c3853246af09420419dfbd352536aa6bb8163d6170e23890"
