name = "uv"
version = "0.12.2"
description = "An extremely fast Python package installer and resolver, written in Rust."
homepage = "https://docs.astral.sh/uv/"
license = "Apache-2.0|MIT"
type = "archive"
bin = ["uv.exe", "uvx.exe", "uvw.exe"]

[architecture.x64]
url = "https://github.com/astral-sh/uv/releases/download/0.12.2/uv-x86_64-pc-windows-msvc.zip"
hash = "sha256:01442d8ce5c7124151a73e697c836d252c6da853c18c73206d3cc4c2378a91d2"
