name = "uv"
version = "0.11.19"
description = "An extremely fast Python package installer and resolver, written in Rust."
homepage = "https://docs.astral.sh/uv/"
license = "Apache-2.0|MIT"
type = "archive"
bin = ["uv.exe", "uvx.exe", "uvw.exe"]

[architecture.x64]
url = "https://github.com/astral-sh/uv/releases/download/0.11.19/uv-x86_64-pc-windows-msvc.zip"
hash = "sha256:1665fc8e37b5d70a134820d6d7891747471a2ac8bc940ee7af0b69fd03b28d61"
