name = "fzf"
version = "0.74.4"
description = "A general-purpose command-line fuzzy finder"
homepage = "https://github.com/junegunn/fzf"
license = "MIT"
type = "archive"
bin = ["fzf.exe"]

[architecture.x64]
url = "https://github.com/junegunn/fzf/releases/download/v0.74.4/fzf-0.74.4-windows_amd64.zip"
hash = "sha256:5e63c0e798406fcb9c51a9fed4988398e25fdabf8c670e32c16caf7b4a7ed02d"
