name = "fzf"
version = "0.74.3"
description = "A general-purpose command-line fuzzy finder"
homepage = "https://github.com/junegunn/fzf"
license = "MIT"
type = "archive"
bin = ["fzf.exe"]

[architecture.x64]
url = "https://github.com/junegunn/fzf/releases/download/v0.74.3/fzf-0.74.3-windows_amd64.zip"
hash = "sha256:cf5c137d9b391c3988c54af8f5fc490ffbef6f70444651e7d57fdb45ad04c8bd"
