name = "nushell-aoks"
version = "0.115.1"
description = "A new type of shell"
homepage = "https://www.nushell.sh/"
license = "MIT"
type = "archive"
bin = ["nu.exe"]

[architecture.x64]
url = "https://github.com/nushell/nushell/releases/download/0.115.1/nu-0.115.1-x86_64-pc-windows-msvc.zip"
hash = "sha256:b83009cbc88021f4dc293c49320118886b78363f9a4bb14933d33c8803241f46"
