name = "nushell-aoks"
version = "0.113.1"
description = "A new type of shell"
homepage = "https://www.nushell.sh/"
license = "MIT"
type = "archive"
bin = ["nu.exe"]

[architecture.x64]
url = "https://github.com/nushell/nushell/releases/download/0.113.1/nu-0.113.1-x86_64-pc-windows-msvc.zip"
hash = "sha256:fd3e56dac9f866d2d3fe2fabd6580c14371afdcec9ddda54624a50986d36b3d2"
