name = "beyondcompare"
version = "5.2.2.32209"
description = "Directory and file compare functions in one package"
homepage = "https://www.scootersoftware.com"
license = "Shareware"
type = "installer"
installer = "innosetup"
bin = ["Bcomp.exe", "BCompare.exe"]

[architecture.x64]
url = "https://www.scootersoftware.com/files/BCompare-5.2.2.32209.exe"
hash = "sha256:11cdb99770d2c8db50c68cf557db4641d1a162bd4362c9b18286ab7a405cf6a1"
