name = "sharex"
version = "21.0.0"
description = "Screen capture, file sharing and productivity tool."
homepage = "https://getsharex.com/"
license = "GPL-3.0-only"
type = "archive"
bin = ["ShareX.exe"]

[architecture.x64]
url = "https://github.com/ShareX/ShareX/releases/download/v21.0.0/ShareX-21.0.0-portable-x64.zip"
hash = "sha256:8124938fa718d702bb08ef29292f0140052bdad03d23b3041b5015054ff1c230"
