name = "steam"
version = "2.10.91.91"
description = "Gaming hardware and software store by Valve Corporation"
homepage = "https://store.steampowered.com/"
license = "Freeware"
type = "archive"
bin = ["Steam.exe"]

[architecture.x64]
url = "https://media.st.dl.eccdnx.com/client/installer/SteamSetup.exe#/dl.7z"
hash = "sha256:7D3654531C32D941B8CAE81C4137FC542172BFA9635F169CB392F245A0A12BCB"
