name = "wechat"
version = "4.1.11.52"
description = "Free messaging and calling app by Tencent"
homepage = "https://www.wechat.com/"
license = "Proprietary"
type = "archive"
bin = ["Weixin.exe"]

[architecture.x64]
url = "https://github.com/cscnk52/wechat-windows-versions/releases/download/v4.1.11.52/weixin_4.1.11.52.exe#/dl.7z"
hash = "sha256:9701600e5d69cbcd23badbfa8ae73bbc7d7fa18d2771e4057184dd02d513dcc2"
