name = "wechat"
version = "4.1.10.53"
description = "Free messaging and calling app by Tencent"
homepage = "https://www.wechat.com/"
license = "Proprietary"
type = "archive"
bin = ["Weixin.exe"]

[architecture.x64]
url = "https://github.com/cscnk52/wechat-windows-versions/releases/download/v4.1.10.53/weixin_4.1.10.53.exe#/dl.7z"
hash = "sha256:ef1130ef1a07092f7606089d4052393d1e26b1cd7ee74a82aab74cab6f487bff"
