name = "wechat"
version = "4.1.13.63"
description = "Free messaging and calling app by Tencent"
homepage = "https://www.wechat.com/"
license = "Proprietary"
type = "archive"
bin = ["Weixin.exe"]

[architecture.x64]
url = "https://github.com/cscnk52/wechat-windows-versions/releases/download/v4.1.13.63/weixin_4.1.13.63.exe#/dl.7z"
hash = "sha256:1c7b83847637bdd708dd5c99f9714c621f0ee8fcdd6ef09b8321d013db979e5d"
